# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers as @s[tag=aj.humanentity.bone.text] run data merge entity @s {"text":"AmadeuszSosna",background:16711680}
execute on passengers as @s[tag=aj.humanentity.bone.l_item] run data merge entity @s {item:{id:"air"}}
execute on passengers as @s[tag=aj.humanentity.bone.r_item] run data merge entity @s {item:{id:"orange_dye",components:{"minecraft:custom_model_data":5}}}
tp @s 7 2 41
title @a times 0 20 20
title @a title {"translate":"\ue001","color":"black"}