# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute as @e[tag=aj.camera] at @s run playsound minecraft:block.stone.step block @a
execute as @a at @s run playsound as:music.whos-that voice @s