# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.zombie.attack_wooden_door block @a ~ ~ ~ 0.4
playsound minecraft:block.wood.break block @a
playsound as:block.door_open block @a
execute positioned 7 2 41 as @e[tag=aj.door.root,limit=1,distance=..1] run function animated_java:door/animations/000_mur_open/play
particle minecraft:block{block_state:{Name:spruce_log}} 7.84 3.00 41.48 0.5 0.5 0.5 0.1 10