# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute as @e[tag=aj.camera] run data merge entity @s {teleport_duration:0}
tp @s 9 15 39
function animated_java:humanentity/animations/000_mur_1/play