# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers as @s[tag=aj.prop.bone.mainprop] run data merge entity @s {item:{id:"endermite_spawn_egg",components:{"minecraft:custom_model_data":50}}}
playsound as:block.woodslide1 ambient @a 13.89 18.17 38.00 0.2