# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound as:sfx.glass.break1 ambient @a 13.69 15.16 37.39 0.5
particle minecraft:block{block_state:{Name:white_concrete}} 13.70 15.00 37.43 0.3 0 0.3 10 10
particle minecraft:block{block_state:{Name:dirt}} 13.86 15.00 36.91 0.2 0.1 0.2 0.1 20
execute as @e[type=minecraft:item_display,x=14.125, y=15.5625, z=36.6875,sort=nearest,limit=1] run data merge entity @s {view_range:1}
execute as @e[type=minecraft:item_display,x=13.875, y=15.5, z=36.75,sort=nearest,limit=1] run data merge entity @s {view_range:1}
execute as @e[type=minecraft:item_display,x=13.75, y=15.5625, z=36.4375,sort=nearest,limit=1] run data merge entity @s {view_range:1}