# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.000_mur_0.frame dummy
scoreboard objectives add aj.000_mur_1.frame dummy
scoreboard objectives add aj.000_mur_2.frame dummy
scoreboard objectives add aj.000_vic_2.frame dummy
scoreboard objectives add aj.000_mur_3.frame dummy
scoreboard objectives add aj.000_vic_3.frame dummy