# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.plant_fall1.frame dummy
scoreboard objectives add aj.bodyblood1.frame dummy