# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon item_display ~ ~ ~ {Tags:['aj.new', 'aj.camera', 'aj.door.camera', 'aj.door.camera.doorlock'], teleport_duration: 2}
execute as @e[type=item_display,tag=aj.new,tag=aj.camera,limit=1,distance=..0.01] run function animated_java:door/zzz/2
data modify entity @s data.cameras.doorlock.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.door.bone.block_display2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_block_display2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.door.bone.block_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.block_display_block_display set from storage aj:uuid main.out