# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.open.frame dummy
scoreboard objectives add aj.close.frame dummy
scoreboard objectives add aj.000_mur_open.frame dummy
scoreboard objectives add aj.000_mur_open2.frame dummy
scoreboard objectives add aj.a_000.frame dummy