# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.prop.root] run return 0
execute on passengers if entity @s[tag=aj.prop.data] unless data entity @s {data:{rigHash: '26a746a1e63f847acddbf5121213f31ac740ecdde653917b6af234ebec3522c0'}} on vehicle run function animated_java:prop/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1