# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute as @e[type=item_display,tag=aj.prop.root] run function animated_java:prop/remove/this