# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.humanentity.root] run return 0
execute on passengers if entity @s[tag=aj.humanentity.data] unless data entity @s {data:{rigHash: '726158947d95a022f0a120e229a3ea062f12e27204614c0ff7b85dc943fd50c4'}} on vehicle run function animated_java:humanentity/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1