# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.humanentity.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:humanentity/as_root/pre_tick
execute if entity @s[tag=aj.humanentity.animation.000_mur_0.playing] run function animated_java:humanentity/animations/000_mur_0/zzz/on_tick
execute if entity @s[tag=aj.humanentity.animation.000_mur_1.playing] run function animated_java:humanentity/animations/000_mur_1/zzz/on_tick
execute if entity @s[tag=aj.humanentity.animation.000_mur_2.playing] run function animated_java:humanentity/animations/000_mur_2/zzz/on_tick
execute if entity @s[tag=aj.humanentity.animation.000_vic_2.playing] run function animated_java:humanentity/animations/000_vic_2/zzz/on_tick
execute if entity @s[tag=aj.humanentity.animation.000_mur_3.playing] run function animated_java:humanentity/animations/000_mur_3/zzz/on_tick
execute if entity @s[tag=aj.humanentity.animation.000_vic_3.playing] run function animated_java:humanentity/animations/000_vic_3/zzz/on_tick
execute on passengers if entity @s[tag=aj.humanentity.data] run function animated_java:humanentity/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:humanentity/as_root/post_tick