# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.door.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'door', 'function_path': 'animated_java:door/animations/a_000/next_frame'}
execute if score @s aj.a_000.frame matches 2.. run scoreboard players set @s aj.a_000.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.a_000.frame
execute at @s run function animated_java:door/animations/a_000/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.a_000.frame 1