# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.humanentity.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'humanentity', 'function_path': 'animated_java:humanentity/variants/a_victim2/apply'}
execute on passengers if entity @s[tag=aj.humanentity.bone.left_eye] run function animated_java:humanentity/variants/a_victim2/zzz/0
execute on passengers if entity @s[tag=aj.humanentity.bone.right_eye] run function animated_java:humanentity/variants/a_victim2/zzz/1
execute on passengers if entity @s[tag=aj.humanentity.bone.right_close] run function animated_java:humanentity/variants/a_victim2/zzz/2
execute on passengers if entity @s[tag=aj.humanentity.bone.left_close] run function animated_java:humanentity/variants/a_victim2/zzz/3
execute on passengers if entity @s[tag=aj.humanentity.bone.left_eyebrow] run function animated_java:humanentity/variants/a_victim2/zzz/4
execute on passengers if entity @s[tag=aj.humanentity.bone.right_eyebrow] run function animated_java:humanentity/variants/a_victim2/zzz/5
execute on passengers if entity @s[tag=aj.humanentity.bone.talking] run function animated_java:humanentity/variants/a_victim2/zzz/6
execute on passengers if entity @s[tag=aj.humanentity.bone.m_opened] run function animated_java:humanentity/variants/a_victim2/zzz/7
execute on passengers if entity @s[tag=aj.humanentity.bone.head] run function animated_java:humanentity/variants/a_victim2/zzz/8
execute on passengers if entity @s[tag=aj.humanentity.bone.rightarm] run function animated_java:humanentity/variants/a_victim2/zzz/9
execute on passengers if entity @s[tag=aj.humanentity.bone.leftarm] run function animated_java:humanentity/variants/a_victim2/zzz/10
execute on passengers if entity @s[tag=aj.humanentity.bone.body] run function animated_java:humanentity/variants/a_victim2/zzz/11
execute on passengers if entity @s[tag=aj.humanentity.bone.leftleg] run function animated_java:humanentity/variants/a_victim2/zzz/12
execute on passengers if entity @s[tag=aj.humanentity.bone.rightleg] run function animated_java:humanentity/variants/a_victim2/zzz/13