# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data merge value {"locators":{},"cameras":{"camera":{"posx":0,"posy":0,"posz":0,"roty":0,"rotx":0}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] run function animated_java:humanentity/variants/a_victim3/apply