# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.door.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'door', 'function_path': 'animated_java:door/animations/pause_all'}
tag @s remove aj.door.animation.open.playing
tag @s remove aj.door.animation.close.playing
tag @s remove aj.door.animation.000_mur_open.playing
tag @s remove aj.door.animation.000_mur_open2.playing
tag @s remove aj.door.animation.a_000.playing