# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data merge value {"locators":{},"cameras":{"doorlock":{"posx":-0.28124999999999994,"posy":0.9375,"posz":-0.375,"roty":0,"rotx":0}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:door/animations/close/zzz/frames/zzz/2