# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.prop.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'prop', 'function_path': 'animated_java:prop/animations/pause_all'}
tag @s remove aj.prop.animation.plant_fall1.playing
tag @s remove aj.prop.animation.bodyblood1.playing