# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon item_display ~ ~ ~ {Tags:['aj.new', 'aj.camera', 'aj.humanentity.camera', 'aj.humanentity.camera.camera'], teleport_duration: 2}
execute as @e[type=item_display,tag=aj.new,tag=aj.camera,limit=1,distance=..0.01] run function animated_java:humanentity/zzz/2
data modify entity @s data.cameras.camera.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.left_eye] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_eye set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.right_eye] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_eye set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.right_close] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_close set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.left_close] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_close set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.left_eyebrow] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_eyebrow set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.right_eyebrow] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_eyebrow set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.talking] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_talking set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.m_opened] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_m_opened set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.r_item] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_r_item set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.rightarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.l_item] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_l_item set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.leftarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.leftleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.rightleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.humanentity.bone.text] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.text_display_text set from storage aj:uuid main.out