# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound as:sfx.gun.shot ambient @a 13.00 16.52 37.10 1 1
particle minecraft:flash 13.00 16.52 37.10
particle minecraft:block{block_state:{Name:redstone_block}} 13.51 16.00 31.61 0.1 0.1 0.1 0.5 30
execute positioned 13 15 31 as @e[tag=aj.humanentity.root,distance=..1,limit=1,sort=nearest] run function animated_java:humanentity/variants/a_victim2/apply