# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function f:missions/tutorial/models/0_shelf
playsound as:sfx.warderobe_hit ambient @a 13.69 16.47 39.00