# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers as @s[tag=aj.humanentity.bone.text] run data merge entity @s {"text":"Presents"}
fill 10 17 41 10 16 41 air
execute positioned 9 15 39 as @e[tag=aj.door.root,limit=1,distance=..1,sort=nearest] run function animated_java:door/animations/000_mur_open2/set_frame {frame:0}