# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:humanentity/animations/000_mur_2/play
execute as @e[tag=aj.camera] run data merge entity @s {teleport_duration:20}