# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute positioned 9 15 39 as @e[tag=aj.door.root,limit=1,distance=..1,sort=nearest] run function animated_java:door/animations/000_mur_open2/play
particle minecraft:flash 9.16 16.04 40.00 0.5 0.5 0.5 0.5 10
playsound as:sfx.gun.shot ambient @a 9.18 16.09 40.00