# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
title @a[tag=player.in_game] times 0 80 0
title @a[tag=player.in_game] title {"translate":"\ue001","color":"black"}
playsound as:sfx.body.hit1 ambient @a 13.16 15.00 30.64
playsound as:sfx.noise ambient @a 13.46 15.00 30.57 0.3