# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound as:sfx.gun.shot ambient @a 13.54 15.00 30.89
execute on passengers as @s[tag=aj.humanentity.bone.text] run data merge entity @s {"text":'"W sieci Kłamstw"'}
fill 12 18 31 12 15 31 air