# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound as:sfx.gun.shot ambient @a 13.54 15.00 30.89
execute positioned 13 15 30 as @e[tag=aj.prop.root,distance=..1] run function animated_java:prop/animations/bodyblood1/play