# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
title @a[tag=player.in_game] times 20 500 20
title @a[tag=player.in_game] title {"translate":"\ue001","color":"black"}