# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
fill 12 18 31 12 15 31 cyan_terracotta
execute as @a at @s run playsound as:cutscene.callunits1 master @s ~ ~ ~
function f:missions/tutorial/models/0_cutend
schedule function f:missions/tutorial/play 20s replace