# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.door.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'door', 'function_path': 'animated_java:door/animations/000_mur_open2/play'}
tag @s add aj.door.animation.000_mur_open2.playing
scoreboard players set @s aj.000_mur_open2.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:door/animations/000_mur_open2/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only